from typing import Any

def image_to_string(image: Any, lang: str | None = None, config: str = '', nice: int = 0, output_type: Any = None, timeout: int = 0) -> str: ...
def get_tesseract_version() -> str: ...