from typing import Any

class Document:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Page: ...
    def close(self) -> None: ...

class Page:
    def get_text(self) -> str: ...
    def get_pixmap(self, matrix: Matrix | None = None) -> Pixmap: ...

class Pixmap:
    width: int
    height: int
    samples: bytes
    def tobytes(self, output: str) -> bytes: ...

class Matrix:
    def __init__(self, x: float, y: float) -> None: ...

def open(filename: str) -> Document: ...